name: Build and Deploy

on:
  push:
    branches:
      - main # Ensure this matches your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: # Grant write access to contents
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace Firebase Config
        run: |
          echo "const firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
            storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}'
          }; export default firebaseConfig;" > firebase-config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Publish the root directory
